# -*- coding: utf-8 -*-
"""SWGOLO7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tdorigo/SWGOLO/blob/main/SWGOLO7.ipynb
"""

#Import all the necessary libraries
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time
import copy
import warnings
import matplotlib.patches as patches
from pathlib import Path
from matplotlib import colors
from matplotlib.colors import LogNorm
from matplotlib.colors import Normalize
from torch.utils.data import TensorDataset, DataLoader

"""# Functions"""

#This function evaluates the specific angular coefficients at given energy value

def Y(energy, f_mode):
    Y = torch.zeros((4, 1))

    #Convert Energy to PeV
    xe = .5 + 20 * (torch.log(energy) - log_01) / (log_10 - log_01)
    xe2 = xe * xe

    #Evaluate Y for given energy and mode
    for i in range(4):
        if f_mode == "mg0":
            Y[i] = torch.exp(PXmg_p[i, 0, 0]) + torch.exp(PXmg_p[i ,0, 1] * torch.pow(xe, PXmg_p[i, 0, 2]))

        elif f_mode == "mg2":
            Y[i] = PXmg_p[i, 2, 0] + PXmg_p[i, 2, 1] * xe + PXmg_p[i, 2, 2] * xe2

        elif f_mode == "eg0":
            Y[i] = PXeg_p[i, 0, 0] * torch.exp(PXeg_p[i, 0, 1] * torch.pow(xe, PXeg_p[i, 0, 2]))

        elif f_mode == "eg1":
            Y[i] = PXeg_p[i, 1, 0] + PXeg_p[i, 1, 1] * xe + PXeg_p[i, 1, 2] * xe2

        elif f_mode == "eg2":
            Y[i] = PXeg_p[i, 2, 0] + PXeg_p[i, 2, 1] * xe + PXeg_p[i, 2, 2] * xe2

        elif f_mode == "mp0":
            Y[i] = torch.exp(PXmp_p[i, 0, 0]) + torch.exp(PXmp_p[i, 0, 1] * torch.pow(xe, PXmp_p[i, 0, 2]))

        elif f_mode == "mp2":
            Y[i] = PXmp_p[i, 2, 0] + PXmp_p[i, 2, 1] * xe + PXmp_p[i, 2, 2] * xe2

        elif f_mode == "ep0":
            Y[i] = torch.exp(PXep_p[i, 0, 0]) + torch.exp(PXep_p[i, 0, 1] * torch.pow(xe, PXep_p[i, 0, 2]))

        elif f_mode == "ep1":
            Y[i] = PXep_p[i, 1, 0] + PXep_p[i, 1, 1] * xe + PXep_p[i, 1, 2] * xe2

        elif f_mode == "ep2":
            Y[i] = PXep_p[i, 2, 0] + PXep_p[i, 2, 1] * xe + PXep_p[i, 2, 2] * xe2

        else:
            warnings.warn("The Mode is not defined")
            return

    return Y

#Interpolated parameter computation
#thisp0 = normalization constant
#thisp1 = slope parameter
#thisp2 = shape parameter

def thisp(energy, theta, f_mode):
    #Find Y values
    Y_val = Y(energy, f_mode)

    #Solve for B
    B = torch.linalg.solve(A, Y_val)

    #Define x from theta
    x = .5 + 4 * theta / theta_max

    res = 0

    for i in range(4):
        res += B[i] * x ** i

    return res

def ReadShowers(path_g, path_p):
    #GAMMA SHOWERS
    #Reading the Electron Parameters in the Showers
    PXeg1_p = np.loadtxt(path_g, max_rows = 3)

    for i in range(3):
        if PXeg1_p[i, 0]*PXeg1_p[i, 1]*PXeg1_p[i, 2] == 0:
            warnings.warn("Encountered 0")
            return

    PXeg2_p = np.loadtxt(path_g, skiprows = 3, max_rows = 3)

    for i in range(3):
        if PXeg2_p[i, 0]*PXeg2_p[i, 1]*PXeg2_p[i, 2] == 0:
            warnings.warn("Encountered 0")
            return

    PXeg3_p = np.loadtxt(path_g, skiprows = 6, max_rows = 3)

    for i in range(3):
        if PXeg3_p[i, 0]*PXeg3_p[i, 1]*PXeg3_p[i, 2] == 0:
            warnings.warn("Encountered 0")
            return

    PXeg4_p = np.loadtxt(path_g, skiprows = 9, max_rows = 3)

    for i in range(3):
        if PXeg4_p[i, 0]*PXeg4_p[i, 1]*PXeg4_p[i, 2] == 0:
            warnings.warn("Encountered 0")
            return

    #Reading the Muon Parameters in the Showers
    PXmg1_p = np.loadtxt(path_g, skiprows = 12, max_rows = 3)

    for i in range(3):
        if PXmg1_p[i, 0]*PXmg1_p[i, 1]*PXmg1_p[i, 2] == 0 and i != 1:
            warnings.warn("Encountered 0")
            return

    PXmg2_p = np.loadtxt(path_g, skiprows = 15, max_rows = 3)

    for i in range(3):
        if PXmg2_p[i, 0]*PXmg2_p[i, 1]*PXmg2_p[i, 2] == 0 and i != 1:
            warnings.warn("Encountered 0")
            return

    PXmg3_p = np.loadtxt(path_g, skiprows = 18, max_rows = 3)

    for i in range(3):
        if PXmg3_p[i, 0]*PXmg3_p[i, 1]*PXmg3_p[i, 2] == 0 and i != 1:
            warnings.warn("Encountered 0")
            return

    PXmg4_p = np.loadtxt(path_g, skiprows = 21, max_rows = 3)

    for i in range(3):
        if PXmg4_p[i, 0]*PXmg4_p[i, 1]*PXmg4_p[i, 2] == 0 and i != 1:
            warnings.warn("Encountered 0")
            return

    #PROTON SHOWERS
    #Reading the Electron Parameters in the Showers
    PXep1_p = np.loadtxt(path_p, max_rows = 3)

    for i in range(3):
        if PXep1_p[i, 0]*PXep1_p[i, 1]*PXep1_p[i, 2] == 0:
            warnings.warn("Encountered 0")
            return

    PXep2_p = np.loadtxt(path_p, skiprows = 3, max_rows = 3)

    for i in range(3):
        if PXep2_p[i, 0]*PXep2_p[i, 1]*PXep2_p[i, 2] == 0:
            warnings.warn("Encountered 0")
            return

    PXep3_p = np.loadtxt(path_p, skiprows = 6, max_rows = 3)

    for i in range(3):
        if PXep3_p[i, 0]*PXep3_p[i, 1]*PXep3_p[i, 2] == 0:
            warnings.warn("Encountered 0")
            return

    PXep4_p = np.loadtxt(path_p, skiprows = 9, max_rows = 3)

    for i in range(3):
        if PXep4_p[i, 0]*PXep4_p[i, 1]*PXep4_p[i, 2] == 0:
            warnings.warn("Encountered 0")
            return

    #Reading the Muon Parameters in the Showers
    PXmp1_p = np.loadtxt(path_p, skiprows = 12, max_rows = 3)

    for i in range(3):
        if PXmp1_p[i, 0]*PXmp1_p[i, 1]*PXmp1_p[i, 2] == 0 and i != 1:
            warnings.warn("Encountered 0")
            return

    PXmp2_p = np.loadtxt(path_p, skiprows = 15, max_rows = 3)

    for i in range(3):
        if PXmp2_p[i, 0]*PXmp2_p[i, 1]*PXmp2_p[i, 2] == 0 and i != 1:
            warnings.warn("Encountered 0")
            return

    PXmp3_p = np.loadtxt(path_p, skiprows = 18, max_rows = 3)

    for i in range(3):
        if PXmp3_p[i, 0]*PXmp3_p[i, 1]*PXmp3_p[i, 2] == 0 and i != 1:
            warnings.warn("Encountered 0")
            return

    PXmp4_p = np.loadtxt(path_p, skiprows = 21, max_rows = 3)

    for i in range(3):
        if PXmp4_p[i, 0]*PXmp4_p[i, 1]*PXmp4_p[i, 2] == 0 and i != 1:
            warnings.warn("Encountered 0")
            return

    PXmg_p = torch.tensor([PXmg1_p, PXmg2_p, PXmg3_p, PXmg4_p])
    PXeg_p = torch.tensor([PXeg1_p, PXeg2_p, PXeg3_p, PXeg4_p])
    PXmp_p = torch.tensor([PXmp1_p, PXmp2_p, PXmp3_p, PXmp4_p])
    PXep_p = torch.tensor([PXep1_p, PXep2_p, PXep3_p, PXep4_p])

    return PXmg_p, PXeg_p, PXmp_p, PXep_p

#This function parametrize the particle species content from the showers
#We find the flux of the particles for a given energy, angle and distance
#f_mode is used to tell the code which particle species we are dealing with, beacuse equation changes
#whether we are dealing with muons or electrons

def ShowerContent(energy, theta, R, f_mode):
    #Check if everything is in the range:
    R = torch.clamp(R, min=R_min)

    if energy < .1 or energy > 10:
        warnings.warn("Energy is out of range!")
        return 0

    if theta < 0 or theta > theta_max:
        warnings.warn("Angle is out of range!")
        return 0

    if f_mode == "mg" or f_mode == "mp":
        thisp0 = thisp(energy, theta, f_mode + "0")
        thisp2 = thisp(energy, theta, f_mode + "2")

        #Evaluate the  Flux
        flux0 = TankArea * .02 * thisp0 * torch.exp(-1 * torch.pow(R, thisp2))

    elif f_mode == "eg" or f_mode == "ep":
        thisp0 = thisp(energy, theta, f_mode + "0")
        thisp1 = thisp(energy, theta, f_mode + "1")
        thisp2 = thisp(energy, theta, f_mode + "2")

        #Evaluate the Flux
        flux0 = TankArea * thisp0 * torch.exp(-thisp1 * torch.pow(R, thisp2))

    else:
        warnings.warn("Mode is not defined")
        return

    #We need to make sure that flux is non negative or too large
    flux0 = torch.clamp(flux0, min=epsilon, max=largenumber)

    return flux0

#This function defines the initial layouts of the detectors, N_det = 90
#At this point of the project, we just define a square grid

def Layouts():
    R = [50, 200, 350, 550, 750, 1000]
    x = []
    y = []

    for i, r in enumerate(R):
        if i == 0:
            for j in range(3):
                x.append(r * np.cos(j *np.pi * 2 / 3))
                y.append(r * np.sin(j *np.pi * 2 / 3))

        if i == 1:
            for j in range(9):
                x.append(r * np.cos(j * np.pi * 2 / 9))
                y.append(r * np.sin(j * np.pi * 2 / 9))

        if i == 2:
            for j in range(12):
                x.append(r * np.cos(j * np.pi * 2 / 12))
                y.append(r * np.sin(j * np.pi * 2 / 12))

        if i == 3:
            for j in range(15):
                x.append(r * np.cos(j * np.pi * 2 / 15))
                y.append(r * np.sin(j * np.pi * 2 / 15))

        if i == 4:
            for j in range(18):
                x.append(r * np.cos(j * np.pi * 2 / 18))
                y.append(r * np.sin(j * np.pi * 2 / 18))

        if i == 5:
            for j in range(33):
                x.append(r * np.cos(j * np.pi * 2 / 33))
                y.append(r * np.sin(j * np.pi * 2 / 33))

    return x, y

#We will generate the showers here, getting the energy, angle, and position of the shower core

def GenerateShowers(x, y):
    #Randomize Hadronic / Gamma Showers
    shower_r = torch.tensor([np.random.rand()], dtype = torch.float32)

    if shower_r >= .5:
        shower_type = "h"
    else:
        shower_type = "g"

    #Define the position of the shower cores
    X0 = torch.tensor([np.random.uniform(-1000, 1000)], dtype = torch.float32)
    Y0 = torch.tensor([np.random.uniform(-1000, 1000)], dtype = torch.float32)

    #Define the energy and angles
    energy = torch.tensor([np.random.uniform(.1, 10)], dtype = torch.float32)
    theta = torch.tensor([np.random.uniform(0, theta_max)], dtype = torch.float32)
    phi = torch.tensor([np.random.uniform(-np.pi, np.pi)], dtype = torch.float32)

    #Debugging part
    if SWGOopt == True:
        #Real distribution of Hadronic and Gamma Showers:
        shower = hg_dist()
        #Shower Core is at origin
        X0 = torch.tensor([np.random.uniform(-3000, 3000)], dtype = torch.float32)
        Y0 = torch.tensor([np.random.uniform(-3000, 3000)], dtype = torch.float32)
        #Energy is 1 PeV
        energy = torch.tensor([powerlawdist()], dtype = torch.float32)
        #30 degree angle of incidence
        theta = torch.tensor([np.random.uniform(0, theta_max)], dtype = torch.float32)

        phi = torch.tensor([np.random.uniform(-np.pi, np.pi)], dtype = torch.float32)

    #Evalute the counts in the tanks
    Ne, Nm, Te, Tm = GetCounts(energy, theta, phi, X0, Y0, x, y, shower_type)

    return Ne, Nm, Te, Tm, X0, Y0, energy, theta, phi, shower_type

#This function gets the counts and the times in detector units
#For each detector we have, first, we evaluate its distance from the shower core
#Then we evaluate the flux by using previously defined ShowerContent function
#Since we detect number of particles, we put the value in poisson distribution
#Then we smear the value, since we have some uncertainty on detecting particles
#For each unit, we store the number of particles detected in our arrays Ne and Nm
#Then we proceed to evalute the arrival time in each detector

def GetCounts(TrueE, TrueTh, TruePhi, TrueX0, TrueY0, x, y, shower_type):
    #Initialize Counts and Times
    Nm_list = []
    Ne_list = []
    Tm_list = []
    Te_list = []

    for idx in range(Nunits):
        #At this part we are evaluating the number of particles detected in each unit
        R = EffectiveDistance(x[idx], y[idx], TrueX0, TrueY0, TrueTh, TruePhi)
        ct = torch.cos(TrueTh)

        #Evaluate the Content
        if shower_type == "g":
            m0 = ShowerContent(TrueE, TrueTh, R, "mg")
            e0 = ShowerContent(TrueE, TrueTh, R, "eg")
        elif shower_type == "h":
            m0 = ShowerContent(TrueE, TrueTh, R, "mp")
            e0 = ShowerContent(TrueE, TrueTh, R, "ep")

        mb = fluxB_m
        eb = fluxB_e

        nms = SmearN(m0 * ct)
        nes = SmearN(e0 * ct)

        nmb = SmearN(fluxB_m)
        neb = SmearN(fluxB_e)

        Nm_i = nms + nmb
        Ne_i = nes + neb

        Nm_list.append(Nm_i)
        Ne_list.append(Ne_i)

        #Handling the timing generation
        et = EffectiveTime(x[idx], y[idx], TrueX0, TrueY0, TrueTh, TruePhi) #expected time of arrival in the unit

        # Conditional times (avoid .item())
        if Ne_i > 0:
            TAe_m, TAe_s = TimeAverage(et, neb, nes)
            Te_list.append(TAe_m + torch.randn_like(TAe_m) * TAe_s)
        else:
            Te_list.append(torch.tensor([0.0]))

        if Nm_i > 0:
            TAm_m, TAm_s = TimeAverage(et, nmb, nms)
            Tm_list.append(TAm_m + torch.randn_like(TAm_m) * TAm_s)
        else:
            Tm_list.append(torch.tensor([0.0]))

    # Stack to form tensors
    Nm = torch.stack(Nm_list)
    Ne = torch.stack(Ne_list)
    Tm = torch.stack(Tm_list)
    Te = torch.stack(Te_list)

    return Ne, Nm, Te, Tm

#This function evaluates the distance of the given unit from the shower core
def EffectiveDistance(xd, yd, x0, y0, th, ph):
    dx = xd - x0
    dy = yd - y0
    t = torch.sin(th) * torch.cos(ph) * dx + torch.sin(th) * torch.sin(ph) * dy
    r = dx ** 2 + dy ** 2 - t ** 2

    r = torch.where(r > 0, torch.sqrt(r), torch.zeros_like(r))  # or any fallback like r=r
    r = torch.clamp(r, min = R_min)

    return r

#This function evaluates the time of arrival of the particles to the ground
#t = 0 for first arrivals while t > 0 for late arrival particles

def EffectiveTime(xd, yd, x0, y0, th, ph):
    et = ((xd - x0) * torch.sin(th) * torch.cos(ph) + (yd - y0) * torch.sin(th) * torch.sin(ph)) / c0

    return et

#We have some resolution in our detectors, which inherently has some uncertainty in detecting the number of particles
#This function accounts for this uncertainty
#We keep a fix resolution, it does not change for different flux values

def SmearN(flux):
    gate = torch.sigmoid(10 * (flux - 0.1))
    noise = torch.randn_like(flux)  # standard normal noise
    noisy = flux + RelResCounts * flux * noise  # reparameterized: mean + std * noise

    return gate * noisy

def TimeAverage(T, Nb, Ns):
    noise = torch.rand_like(T) - .5

    if Nb <= 1:
        STbgr = IntegrationWindow / sqrt12
        AvTbgr = T + noise * STbgr

    elif Nb <= 2:
        STbgr = IntegrationWindow * .2041
        AvTbgr = T + noise * STbgr

    elif Nb <= 3:
        STbgr = IntegrationWindow * .166666
        AvTbgr = T + noise * STbgr

    elif Nb <= 4:
        STbgr = IntegrationWindow * .1445
        AvTbgr = T + noise * STbgr

    else:
        STbgr = IntegrationWindow * .11
        AvTbgr = torch.normal(T, STbgr)

        while (AvTbgr - T > .5 * IntegrationWindow):
            AvTbgr = torch.normal(T, STbgr)

    STsig = sigma_time

    if Ns >= 2:
        STsig = sigma_time / torch.sqrt(Ns - 1)

    AvTsig = T + torch.randn_like(T) * STsig

    if Nb == 0 and Ns == 0:
        mean = T
        std = IntegrationWindow / sqrt12

    elif Nb == 0:
        mean = AvTsig
        std = STsig

    elif Ns == 0:
        mean = AvTbgr
        std = STbgr

    else:
        w_bgr = 1.0 / (STbgr ** 2)
        w_sig = 1.0 / (STsig ** 2)
        sum_weights = w_bgr + w_sig

        mean = (AvTsig * w_sig + AvTbgr * w_bgr) / sum_weights
        std = torch.sqrt(1.0 / sum_weights)

    return mean, std

def powerlawdist(E_min = 0.1, E_max = 10, index = 2.7):
    # Inverse transform sampling
    r = np.random.rand()
    exponent = 1.0 - index
    Emin_pow = E_min**exponent
    Emax_pow = E_max**exponent
    energies = (Emin_pow + r * (Emax_pow - Emin_pow)) ** (1.0 / exponent)

    return energies

def hg_dist():
    r = np.random.rand()

    if r <= 1e-4:
        shower = "g"
    else:
        shower = "h"

    return shower

def symmetry_loss(x, y, n_symmetry = 3, center = (0.0, 0.0)):
    #Penalizes deviation from n-fold rotational symmetry without relying on grouping.
    #Matches each rotated point to its nearest neighbor in the original set.
    x_centered = x - center[0]
    y_centered = y - center[1]
    coords = torch.stack([x_centered, y_centered], dim=1)  # (N, 2)

    sym_loss = 0.0
    for i in range(1, n_symmetry):
        theta = 2 * np.pi * i / n_symmetry
        R = torch.tensor([
            [np.cos(theta), -np.sin(theta)],
            [np.sin(theta),  np.cos(theta)]
        ], dtype=coords.dtype, device=coords.device)

        rotated = coords @ R.T  # (N, 2)

        # Compute pairwise distances between rotated and original coords
        dists = torch.cdist(rotated, coords, p=2)  # (N, N)

        # Find nearest neighbor for each rotated point
        min_dists, _ = dists.min(dim=1)

        sym_loss += min_dists.mean()

    return sym_loss / (n_symmetry - 1)

def shower_converter(s):
    if s == "h":
        b = 1.0
    elif s == "g":
        b = .0
    else:
        warnings.warn("Shower type is not defined!")

    return b

def shower_identification(v):
    if v >= .5:
        t = "h"
    elif 0 <= v and v < .5:
        t = "g"
    else:
        warnings.warn("Shower type is not defined!")

    return t

"""## Utilities"""

def reconstructability(events):
    layout_threshold = 5. #We accept the arrays detecting >= 5 particles
    tau_layout = 5.
    reconstruct_threshold = 3.
    tau_reconstruct = 5.

    soft_detect = torch.sigmoid(tau_layout * (events - layout_threshold))
    n = torch.sum(soft_detect, dim = 1)

    r = torch.sigmoid(tau_reconstruct * (n - reconstruct_threshold))

    return r

#I will try to smooth the function and make it differentiable for PyTorch, the code is below, I am not 100% sure if this
#code translates exactly what I want to do, but we can check

def U_PR(r):
    u = torch.sqrt(torch.sum(r) + 1e-6) #1e-6 is for stability

    return u

def U_E(E_preds, E_trues, r):
    u = torch.sum(r / ((E_preds - E_trues) ** 2 + .01))

    return u

def U_TH(Th_preds, Th_trues, r):
    u = torch.sum(r / ((Th_preds - Th_trues) ** 2 + .00001))

    return u

"""# Neural Network

In this section we are creating our neural network, we will train it with some simulated EAS. the idea is to feed the network with detector positions, with detected number of particles, and time of arrival. Then we neural network output will be energy of the shower, angles, and shower core (X, Y)

We have to determine the number of hidden layers and number of neurons by hand, as there is no optimization regarding these parameters.

We will keep learning rate small, ie. lr = 1e-5, otherwise NN tends to overfit

It might be argued that for the first part there is no reason to keep positions of the detectors as inputs in our network, but that part will be useful when we need to train our NN again for new positions.
"""

class Reconstruction(nn.Module):
    def __init__(self, input_features = 6, num_detectors = 90, hidden_lay1 = 512, hidden_lay2 = 256,
                 hidden_lay3 = 128, hidden_lay4 = 64, hidden_lay5 = 32, output_dim = 7):
        super(Reconstruction, self).__init__()
        self.num_detectors = num_detectors
        self.input_features = input_features

        #We have to flatten the input, since we are using fully connected neural network
        self.L1 = nn.Linear(num_detectors * input_features, hidden_lay1)
        self.L2 = nn.Linear(hidden_lay1, hidden_lay2)
        self.L3 = nn.Linear(hidden_lay2, hidden_lay3)
        self.L4 = nn.Linear(hidden_lay3, hidden_lay4)
        self.L5 = nn.Linear(hidden_lay4, hidden_lay5)
        self.L6 = nn.Linear(hidden_lay5, output_dim)
        self.tanh = nn.Tanh()
        self.relu = nn.ReLU()
        self.sig = nn.Sigmoid()
        self.dropout = nn.Dropout(0.1) #This way we drop a fraction of the neurons randomly at iteration,
        #So that our network won't rely on some specific network path

        #Output_dim = 6 means: we will have an output containing (X0, Y0, E0, Theta0, Phi0, Shower_type)

    def forward(self, x):
        out = self.L1(x)
        out = self.relu(out)
        out = self.dropout(out)
        out = self.L2(out)
        out = self.relu(out)
        out = self.L3(out)
        out = self.relu(out)
        out = self.L4(out)
        out = self.relu(out)
        out = self.L5(out)
        out = self.relu(out)
        out = self.L6(out)

        class_out = self.sig(out[:, 6:7])
        param_out = self.tanh(out[:, 0:4])
        phi_out = out[:, 4:6]

        return torch.cat([param_out, phi_out, class_out], dim = 1)

#These functions are needed to normalize the labels and denormalize the outputs, otherwise the scales change too much that
#NN training will fail
def NormalizeLabels(E, theta, phi):
    E_norm = 2 * (E - .1) / (10 - .1) - 1
    theta_norm = 2 * theta / (theta_max) - 1
    sin = torch.sin(phi)
    cos = torch.cos(phi)

    return E_norm, theta_norm, sin, cos

def DenormalizeLabels(E_norm, theta_norm, sin, cos):
    E = 0.1 + (E_norm + 1) * (10 - 0.1) / 2
    theta = (theta_norm + 1) * theta_max / 2
    phi = torch.atan2(sin, cos)

    return E, theta, phi

#We use this class in the case of early stop
#If our network stops improving after some time there is no need to continue

class EarlyStopping:
    def __init__(self, patience = 20, min_delta = 1e-4):
        self.patience = patience
        self.min_delta = min_delta
        self.best_loss = float('inf')
        self.counter = 0
        self.early_stop = False

    def __call__(self, val_loss):
        if val_loss < self.best_loss - self.min_delta:
            self.best_loss = val_loss
            self.counter = 0
        else:
            self.counter += 1
            if self.counter >= self.patience:
                self.early_stop = True

"""# Global Variables"""

#Matrices we use in the functions
PXmg_p, PXeg_p, PXmp_p, PXep_p = ReadShowers("./Fit_Photon_10_pars.txt", "./Fit_Proton_2_pars.txt")
A = torch.tensor([[1, 1, 1, 1],[1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]] , dtype = torch.float32)

#Constants
c0 = .29979 #Speed of light in [m / ns] units
theta_max = np.pi * 65 / 180
log_01 = torch.tensor([np.log(.1)], dtype = torch.float32)
log_10 = torch.tensor([np.log(10)], dtype = torch.float32)
sqrt12 = torch.tensor([np.sqrt(12)], dtype = torch.float32)

#Tank Values
IntegrationWindow = 128. #128 ns integration window, SWGO default
sigma_time = 10. #Time resolution assumed for the detectors
R_min = 2.
TankArea = 68.59 * np.pi #Area for 19 hexagonal macro unit
TankRadius = np.sqrt(68.59) #Radius of macro unit

#Background
Bgr_mu_per_m2 = 0.000001826 * IntegrationWindow
fluxB_m = torch.tensor([TankArea * Bgr_mu_per_m2])

Bgr_e_per_m2 = 0.000000200 * IntegrationWindow
fluxB_e = torch.tensor([TankArea * Bgr_e_per_m2])

#Sizes
Nunits = 90
RelResCounts = .05

#Debug Parameters
largenumber = 1e13
epsilon = 1 / largenumber

#NN
Nevents = 200000
Nvalidation = 20000

#Layout
SWGOopt = False
x, y = Layouts()

x = torch.tensor(x, dtype = torch.float32)
y = torch.tensor(y, dtype = torch.float32)

"""# Main Routine
We will be using here for debugging as well

## Checks
"""

energy = torch.tensor([2.], requires_grad = True)
theta = torch.tensor([np.pi / 6], requires_grad = True)
R = torch.tensor(np.linspace(0, 1000, 500), requires_grad = True)
fluxes = []

for r in R:
    fluxes.append(ShowerContent(energy, theta, r, "mp").item())

plt.plot(R.detach().numpy(), fluxes, linewidth = 2)
plt.grid()
plt.yscale('log')
plt.ylabel("Flux")
plt.xlabel("R [m]")
plt.xlim((0, 1000))
plt.show()

energy = torch.tensor([2.], requires_grad = True)
theta = torch.tensor([np.pi / 6], requires_grad = True)
R = torch.tensor(np.linspace(0, 1000, 500), requires_grad = True)
fluxes = []

for r in R:
    fluxes.append(ShowerContent(energy, theta, r, "ep").item())

plt.plot(R.detach().numpy(), fluxes, linewidth = 2)
plt.grid()
plt.yscale('log')
plt.ylabel("Flux")
plt.xlabel("R [m]")
plt.xlim((0, 1000))
plt.show()

plt.figure(figsize = [6, 6])
plt.scatter(x.detach(), y.detach(), color = "red")
plt.grid()
plt.xlabel("x [m]")
plt.ylabel("y [m]")
plt.title("Initial Position of the detectors")
plt.xlim((-1100, 1100))
plt.ylim((-1100, 1100))
plt.show()

SWGOopt = False

Ne, Nm, Te, Tm, x0, y0, E, th, ph, shower_type = GenerateShowers(x, y)

print(f"Energy = {E.item():.3f} PeV")
print(f"Angle = {th.item() * 180 / np.pi:.1f} degree")

if shower_type == "g":
    s = "Gamma"

elif shower_type == "h":
    s = "Proton"

fig, axs = plt.subplots(1, 2, figsize=(14, 6), sharex=True, sharey=True)

# --- MUONIC COMPONENT ---
idx_mu = torch.where(Nm >= 1)[0]
norm = LogNorm(vmin = 2, vmax = torch.max(Nm).item())

scatter_mu = axs[0].scatter(x[idx_mu], y[idx_mu], c = Nm[idx_mu], cmap = "plasma", norm = norm)
axs[0].scatter(x0.item(), y0.item(), c = "red", marker = "d")
axs[0].set_title("Muon Component")
axs[0].set_xlabel("x [m]")
axs[0].set_ylabel("y [m]")
axs[0].set_xlim(-1100, 1100)
axs[0].set_ylim(-1100, 1100)
cbar_mu = fig.colorbar(scatter_mu, ax=axs[0])
cbar_mu.set_label("Number of detected muons")

# --- ELECTROMAGNETIC COMPONENT ---
idx_e = torch.where(Ne >= 1)[0]
norm = LogNorm(vmin = 2, vmax = torch.max(Ne).item())

scatter_em = axs[1].scatter(x[idx_e], y[idx_e], c = Ne[idx_e], cmap = "plasma", norm = norm)
axs[1].scatter(x0.item(), y0.item(), c = "red", marker = "d")
axs[1].set_title("Electromagnetic Component")
axs[1].set_xlabel("x [m]")
axs[1].set_xlim(-1100, 1100)
axs[1].set_ylim(-1100, 1100)
cbar_em = fig.colorbar(scatter_em, ax=axs[1])
cbar_em.set_label("Number of detected e±")

fig.suptitle(f"Detected Particles for a {s} shower with energy E = {E.item():.2f} PeV")
plt.tight_layout()
plt.show()

# indices where you have at least 1 detected particle
idx_mu = torch.where(Nm >= 1)[0]
idx_e  = torch.where(Ne >= 1)[0]

fig, axes = plt.subplots(1, 2, figsize=(12, 6), sharex=True, sharey=True)

# --- Muons ---
norm = Normalize(vmin = torch.min(Tm), vmax = torch.max(Tm))
sc_mu = axes[0].scatter(x[idx_mu], y[idx_mu], c = Tm[idx_mu], cmap = "plasma", norm = norm)
axes[0].scatter(x0.item(), y0.item(), c = "green", marker = "d", label = "Core")
axes[0].set_title("Muon Time of Arrival")
axes[0].set_xlabel("x [m]")
axes[0].set_ylabel("y [m]")
axes[0].set_xlim((-1100, 1100))
axes[0].set_ylim((-1100, 1100))
fig.colorbar(sc_mu, ax=axes[0], label="Time of Arrival [ns]")

# --- Electrons ---
norm = Normalize(vmin = torch.min(Te), vmax = torch.max(Te))
sc_e = axes[1].scatter(x[idx_e], y[idx_e], c = Te[idx_e], cmap = "plasma", norm = norm)
axes[1].scatter(x0.item(), y0.item(), c = "green", marker = "d", label = "Core")
axes[1].set_title("Electron Time of Arrival")
axes[1].set_xlabel("x [m]")
axes[1].set_xlim((-1100, 1100))
axes[1].set_ylim((-1100, 1100))
fig.colorbar(sc_e, ax=axes[1], label="Time of Arrival [ns]")

# --- Common title ---
fig.suptitle(f"Time of Arrival for a {s} shower with E = {E.item():.2f} PeV", fontsize=14)
plt.tight_layout()
plt.show()

"""## Training the Network

We first need some simulations to train our neural network. In the global variables part, you will find a variable num_events, which is set to 10000. We will use this number to generate random events.

### Test Data Generation

Number of showers in the test set = 200k
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# inputs = torch.zeros((Nevents, Nunits, 6))
# labels = torch.zeros((Nevents, 7))
# 
# for i in range(Nevents):
#     Ne, Nm, Te, Tm, x0, y0, E, theta, phi, shower_type = GenerateShowers(x, y)
# 
#     #Normalize the Labels:
#     E_norm, theta_norm, sin, cos = NormalizeLabels(E, theta, phi)
#     x0 = x0 / 5000 #[km]
#     y0 = y0 / 5000 #[km]
#     shower_value = shower_converter(shower_type)
# 
#     input_vector = np.column_stack((x, y, Ne, Nm, Te, Tm))
# 
#     inputs[i] = torch.tensor(input_vector, dtype = torch.float32)
#     labels[i] = torch.tensor([x0, y0, E_norm, theta_norm, sin, cos, shower_value], dtype = torch.float32)
# 
#     if (i + 1) % 3000 == 0:
#         print(f"Shower generation is {int((i + 1) / 300)}% done")
# 
# torch.save(inputs, "./NN_Files/inputs.pt")
# torch.save(labels, "./NN_Files/labels.pt")

"""### Validation Set Data Generation

Number of events in the validation set = 20k, i.e 10% of the training set
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# inputs_val = torch.zeros((Nvalidation, Nunits, 6))
# labels_val = torch.zeros((Nvalidation, 7))
# 
# for i in range(Nvalidation):
#     Ne, Nm, Te, Tm, x0, y0, E, theta, phi, shower_type = GenerateShowers(x, y)
# 
#     #Normalize the Labels:
#     E_norm, theta_norm, sin, cos = NormalizeLabels(E, theta, phi)
#     x0 = x0 / 5000 #[km]
#     y0 = y0 / 5000 #[km]
#     shower_value = shower_converter(shower_type)
# 
#     input_vector = np.column_stack((x, y, Ne, Nm, Te, Tm))
# 
#     inputs_val[i] = torch.tensor(input_vector, dtype = torch.float32)
#     labels_val[i] = torch.tensor([x0, y0, E_norm, theta_norm, sin, cos, shower_value], dtype = torch.float32)
# 
#     if (i + 1) % 2000 == 0:
#         print(f"Shower generation is {int((i + 1) / 200)}% done")
# 
# torch.save(inputs_val, "./NN_Files/inputs_val.pt")
# torch.save(labels_val, "./NN_Files/labels_val1pt")

"""### Load the Sets"""

inputs = torch.load("./NN_Files/inputs.pt")
labels = torch.load("./NN_Files/labels.pt")

inputs_val = torch.load("./NN_Files/inputs_val.pt")
labels_val = torch.load("./NN_Files/labels_val.pt")

"""### Model"""

#In this part we are defining our model, which is the Neural network for our reconstruction
#We will use Mean Square Error Loss
#Optimization model is SGD, to keep consistent with our next steps

model = Reconstruction()
criterion_cont = nn.MSELoss()
criterion_type = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 1e-4)

dataset = TensorDataset(inputs, labels)

dataloader = DataLoader(dataset, batch_size = 512, shuffle = True, drop_last = True, num_workers = 4)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# val_losses = []
# losses = []
# 
# early_stopper = EarlyStopping()
# 
# for num_epoch in range(1000):
#     model.train()
# 
#     epoch_loss = 0
#     total_batch = 0
# 
#     for batch_inputs, batch_labels in dataloader:
#         batch_size = batch_inputs.size(0)
# 
#         train_x = batch_inputs.view(batch_size, -1)
# 
#         train_y = batch_labels.view(batch_size, -1)
# 
#         #Train the network
#         outputs = model(train_x)
# 
# 
#         loss = .05 * criterion_cont(outputs[:, :6], train_y[:, :6]) + criterion_type(outputs[:, 6].unsqueeze(1)
#                                                                                , train_y[:, 6].unsqueeze(1))
#         epoch_loss += loss.item()
#         total_batch += 1
# 
#         loss.backward()
#         optimizer.step()
# 
#         optimizer.zero_grad()
# 
#     #See if our loss in our validation set improves:
#     val_size = inputs_val.size(0)
# 
#     val_x = inputs_val.view(val_size, -1)
#     val_y = labels_val.view(val_size, -1)
# 
#     model.eval()
# 
#     with torch.no_grad():
# 
#         val_output = model(val_x)
#         val_loss = .01 * criterion_cont(val_output[:, :6], val_y[:, :6]) + criterion_type(val_output[:, 6].unsqueeze(1)
#                                                                                     , val_y[:, 6].unsqueeze(1))
# 
#     val_losses.append(val_loss.item())
#     early_stopper(val_loss)
# 
#     if (num_epoch + 1) % 100 == 0:
#         print(f"Training is {int((num_epoch + 1) / 10)}% done, with Loss = {val_loss:.2f}")
# 
#     losses.append(epoch_loss / total_batch)
# 
#     if early_stopper.early_stop:
#         print(f"Early stop at epoch {num_epoch + 1}")
#         print(f"Validation loss = {val_loss:.2f}")
#         print(f"Training loss = {epoch_loss / total_batch:.2f}")
#         break
# 
# plt.plot(np.arange(1, len(losses) + 1), losses, color = "blue", label = "Training Loss")
# plt.plot(np.arange(1, len(val_losses) + 1), val_losses, color = "red", label = "Validation Loss")
# plt.legend()
# plt.xlabel("Epoch")
# plt.ylabel("Loss")
# plt.grid()

torch.save(model.state_dict(), './NN_files/model_weights.pth')
model.load_state_dict(torch.load('./NN_files/model_weights.pth'))

E_r = []
E_p = []

X_r = []
X_p = []

Y_r = []
Y_p = []

Th_r = []
Th_p = []

Ph_r = []
Ph_p = []

Type_r = []
Type_p = []

for i in range(3000):
    Ne, Nm, Te, Tm, x0, y0, E, th, ph, shower_type = GenerateShowers(x, y)
    X = torch.tensor(np.column_stack((x, y, Ne, Nm, Te, Tm)), dtype = torch.float32)
    X = X.view(1, -1)

    model.eval()

    with torch.no_grad():
        output = model(X)

    x_pred = output[0, 0]
    y_pred = output[0, 1]
    E_pred = output[0, 2]

    theta_pred = output[0, 3]
    sin_pred = output[0, 4]
    cos_pred  = output[0, 5]
    value_pred = output[0,6]

    E_pred, theta_pred, phi_pred = DenormalizeLabels(E_pred, theta_pred, sin_pred, cos_pred)
    type_pred = shower_identification(value_pred)

    E_p.append(E_pred)
    E_r.append(E.item())

    X_r.append(x0.item())
    X_p.append(x_pred * 5000)

    Y_r.append(y0.item())
    Y_p.append(y_pred * 5000)

    Th_r.append(th.item())
    Th_p.append(theta_pred)

    Ph_r.append(ph.item())
    Ph_p.append(phi_pred)

    Type_r.append(shower_type)
    Type_p.append(type_pred)

    if (i + 1) % 1500 == 0:
        print(f"Predicted: {E_pred:.1f}, Real: {E.item():.1f}")

Type_r = np.array(Type_r).ravel()
Type_p = np.array(Type_p).ravel()
fig, axs = plt.subplots(1, 2, figsize=(14, 6), sharex=True, sharey=True)

# --- MUONIC COMPONENT ---
idx_h = np.where(Type_r == "h")[0]
color_map = {"h": "green", "g": "red"}
colors = [color_map[t] for t in Type_p[idx_h]]
axs[0].scatter(np.array(E_r)[idx_h], np.array(E_p)[idx_h], alpha = .5, c = colors)
axs[0].plot(np.arange(.1, 10, .01), np.arange(.1, 10, .01), color = "black", linewidth = 4)
axs[0].set_title("Predictions of Proton Showers")
axs[0].set_xlabel("True E")
axs[0].set_ylabel("Predicted E")
axs[0].set_xlim(0.1, 10.1)
axs[0].set_ylim(0.1, 10.1)

# --- ELECTROMAGNETIC COMPONENT ---

idx_g = np.where(Type_r == "g")[0]
color_map = {"g": "green", "h": "red"}
colors = [color_map[t] for t in Type_p[idx_g]]

axs[1].scatter(np.array(E_r)[idx_g], np.array(E_p)[idx_g], alpha = .5, c = colors)
axs[1].plot(np.arange(.1, 10, .01), np.arange(.1, 10, .01), color = "black", linewidth = 4)
axs[1].set_title("Predictions of Gamma Showers")
axs[1].set_xlabel("True E")
axs[1].set_ylabel("Predicted E")
axs[1].set_xlim(0.1, 10.1)
axs[1].set_ylim(0.1, 10.1)

fig.suptitle("Energy Predictions of EASs")
plt.tight_layout()
plt.show()

fig, axs = plt.subplots(1, 2, figsize=(14, 6), sharex=True, sharey=True)

# --- MUONIC COMPONENT ---
idx_h = np.where(Type_r == "h")[0]
color_map = {"h": "green", "g": "red"}
colors = [color_map[t] for t in Type_p[idx_h]]
axs[0].scatter(np.array(X_r)[idx_h], np.array(X_p)[idx_h], alpha = .5, c = colors)
axs[0].plot(np.arange(-1000, 1000, 1), np.arange(-1000, 1000, 1), color = "black", linewidth = 4)
axs[0].set_title("Predictions of Proton Showers")
axs[0].set_xlabel("True X")
axs[0].set_ylabel("Predicted X")
axs[0].set_xlim(-1000, 1000)
axs[0].set_ylim(-1000, 1000)

# --- ELECTROMAGNETIC COMPONENT ---

idx_g = np.where(Type_r == "g")[0]
color_map = {"g": "green", "h": "red"}
colors = [color_map[t] for t in Type_p[idx_g]]

axs[1].scatter(np.array(X_r)[idx_g], np.array(X_p)[idx_g], alpha = .5, c = colors)
axs[1].plot(np.arange(-1000, 1000, 1), np.arange(-1000, 1000, 1), color = "black", linewidth = 4)
axs[1].set_title("Predictions of Gamma Showers")
axs[1].set_xlabel("True X")
axs[1].set_ylabel("Predicted X")
axs[1].set_xlim(-1000, 1000)
axs[1].set_ylim(-1000, 1000)

fig.suptitle("X Predictions of EASs")
plt.tight_layout()
plt.show()

fig, axs = plt.subplots(1, 2, figsize=(14, 6), sharex=True, sharey=True)

# --- MUONIC COMPONENT ---
idx_h = np.where(Type_r == "h")[0]
color_map = {"h": "green", "g": "red"}
colors = [color_map[t] for t in Type_p[idx_h]]
axs[0].scatter(np.array(Y_r)[idx_h], np.array(Y_p)[idx_h], alpha = .5, c = colors)
axs[0].plot(np.arange(-1000, 1000, 1), np.arange(-1000, 1000, 1), color = "black", linewidth = 4)
axs[0].set_title("Predictions of Proton Showers")
axs[0].set_xlabel("True Y")
axs[0].set_ylabel("Predicted Y")
axs[0].set_xlim(-1000, 1000)
axs[0].set_ylim(-1000, 1000)

# --- ELECTROMAGNETIC COMPONENT ---

idx_g = np.where(Type_r == "g")[0]
color_map = {"g": "green", "h": "red"}
colors = [color_map[t] for t in Type_p[idx_g]]

axs[1].scatter(np.array(Y_r)[idx_g], np.array(Y_p)[idx_g], alpha = .5, c = colors)
axs[1].plot(np.arange(-1000, 1000, 1), np.arange(-1000, 1000, 1), color = "black", linewidth = 4)
axs[1].set_title("Predictions of Gamma Showers")
axs[1].set_xlabel("True Y")
axs[1].set_ylabel("Predicted Y")
axs[1].set_xlim(-1000, 1000)
axs[1].set_ylim(-1000, 1000)

fig.suptitle("Y Predictions of EASs")
plt.tight_layout()
plt.show()

fig, axs = plt.subplots(1, 2, figsize=(14, 6), sharex=True, sharey=True)

# --- MUONIC COMPONENT ---
idx_h = np.where(Type_r == "h")[0]
color_map = {"h": "green", "g": "red"}
colors = [color_map[t] for t in Type_p[idx_h]]
axs[0].scatter(np.array(Th_r)[idx_h], np.array(Th_p)[idx_h], alpha = .5, c = colors)
axs[0].plot(np.arange(0, np.pi * 65 / 180, .01), np.arange(0, np.pi * 65 / 180, .01), color = "black", linewidth = 4)
axs[0].set_title("Predictions of Proton Showers")
axs[0].set_xlabel("True Th")
axs[0].set_ylabel("Predicted Th")
axs[0].set_xlim(0, np.pi * 65 / 180)
axs[0].set_ylim(0, np.pi * 65 / 180)

# --- ELECTROMAGNETIC COMPONENT ---

idx_g = np.where(Type_r == "g")[0]
color_map = {"g": "green", "h": "red"}
colors = [color_map[t] for t in Type_p[idx_g]]

axs[1].scatter(np.array(Th_r)[idx_g], np.array(Th_p)[idx_g], alpha = .5, c = colors)
axs[1].plot(np.arange(0, np.pi * 65 / 180, .01), np.arange(0, np.pi * 65 / 180, .01), color = "black", linewidth = 4)
axs[1].set_title("Predictions of Gamma Showers")
axs[1].set_xlabel("True Th")
axs[1].set_ylabel("Predicted Th")
axs[1].set_xlim(0, np.pi * 65 / 180)
axs[1].set_ylim(0, np.pi * 65 / 180)

fig.suptitle("Theta Predictions of EASs")
plt.tight_layout()
plt.show()

fig, axs = plt.subplots(1, 2, figsize=(14, 6), sharex=True, sharey=True)

# --- MUONIC COMPONENT ---
idx_h = np.where(Type_r == "h")[0]
color_map = {"h": "green", "g": "red"}
colors = [color_map[t] for t in Type_p[idx_h]]
axs[0].scatter(np.array(Ph_r)[idx_h], np.array(Ph_p)[idx_h], alpha = .5, c = colors)
axs[0].plot(np.arange(-np.pi, np.pi, .01), np.arange(-np.pi, np.pi, .01), color = "black", linewidth = 4)
axs[0].set_title("Predictions of Proton Showers")
axs[0].set_xlabel("True Ph")
axs[0].set_ylabel("Predicted Ph")
axs[0].set_xlim(-np.pi, np.pi)
axs[0].set_ylim(-np.pi, np.pi)

# --- ELECTROMAGNETIC COMPONENT ---

idx_g = np.where(Type_r == "g")[0]
color_map = {"g": "green", "h": "red"}
colors = [color_map[t] for t in Type_p[idx_g]]

axs[1].scatter(np.array(Ph_r)[idx_g], np.array(Ph_p)[idx_g], alpha = .5, c = colors)
axs[1].plot(np.arange(-np.pi, np.pi, .01), np.arange(-np.pi, np.pi, .01), color = "black", linewidth = 4)
axs[1].set_title("Predictions of Gamma Showers")
axs[1].set_xlabel("True Ph")
axs[1].set_ylabel("Predicted Ph")
axs[1].set_xlim(-np.pi, np.pi)
axs[1].set_ylim(-np.pi, np.pi)

fig.suptitle("Phi Predictions of EASs")
plt.tight_layout()
plt.show()

data = np.abs(np.array(Y_p) - np.array(Y_r))
idx_low = np.where(np.array(E_r) <= 3.)
idx_mid = np.where((np.array(E_r) <= 5.) & (np.array(E_r) > 3.))
idx_high = np.where(np.array(E_r) > 5.)

bin_high = np.logspace(np.log10(min(data[idx_high])), np.log10(max(data[idx_high])), 50)
bin_mid = np.logspace(np.log10(min(data[idx_mid])), np.log10(max(data[idx_mid])), 50)
bin_low = np.logspace(np.log10(min(data[idx_low])), np.log10(max(data[idx_low])), 50)

plt.hist(data[idx_high], bins = bin_high, alpha = .5, color = "blue", label = "High Energy Events")
plt.hist(data[idx_mid], bins = bin_mid, alpha = .5, color = "yellow", label = "Medium Energy Events")
plt.hist(data[idx_low], bins = bin_low, alpha = .5, color = "red", label = "Low Energy Events")
plt.xlabel("Core Position Y Loss")
plt.legend()
plt.xscale("log")
plt.ylabel("Counts")
plt.grid()
plt.show()

"""## Optimization

This is part where we start moving our arrays according to Utility Function.

You can check the utilities that we use above and see that it is > 0

So we will use -U as a "loss" function and minimize it, so that we can maximize our value
"""

#First save the weights or load them so that we don't have to train the network every time we start the kernel
#Remove the commend operator "#" if you want to save

#torch.save(model.state_dict(), './NN_files/model_weights.pth')

model = Reconstruction()

path = Path("./NN_Files/checkpoint.pth")

if path.exists():
    checkpoint = torch.load('./NN_Files/checkpoint.pth')

    model.load_state_dict(checkpoint['model_state_dict'])
    print("Updated Weights are loaded")

else:
    model.load_state_dict(torch.load('./NN_files/model_weights.pth'))
    print("Initial Weights are loaded")

def barycentric_coords(P, A, B, C):
    """
    Compute barycentric coordinates for each point P with respect to triangle ABC.
    P: Tensor of shape (N, 2)
    A, B, C: Tensors of shape (2,)
    """
    v0 = C - A
    v1 = B - A
    v2 = P - A

    d00 = v0 @ v0
    d01 = v0 @ v1
    d11 = v1 @ v1
    d20 = torch.sum(v2 * v0, dim=1)
    d21 = torch.sum(v2 * v1, dim=1)

    denom = d00 * d11 - d01 * d01 + 1e-8
    u = (d11 * d20 - d01 * d21) / denom
    v = (d00 * d21 - d01 * d20) / denom
    return u, v

def project_to_triangle(x, y):
    """
    Projects each (x[i], y[i]) point inside the triangle defined by:
    A = (-3200, 2000), B = (1800, 2000), C = (1800, -3600)
    x, y: tensors of shape (N,)
    Returns: projected x and y, tensors of shape (N,)
    """
    A = torch.tensor([-3800.0, 1500.0], device=x.device)
    B = torch.tensor([1200.0, 1500.0], device=x.device)
    C = torch.tensor([1200.0, -4100.0], device=x.device)

    P = torch.stack([x, y], dim=1)  # (N, 2)

    # Compute barycentric coordinates
    u, v = barycentric_coords(P, A, B, C)

    # Determine which points are inside the triangle
    inside = (u >= 0) & (v >= 0) & (u + v <= 1)

    # Clip to triangle: u, v ∈ [0, 1], u + v ≤ 1
    u_clipped = torch.clamp(u, 0.0, 1.0)
    v_clipped = torch.clamp(v, 0.0, 1.0)
    uv_sum = u_clipped + v_clipped
    over = uv_sum > 1.0
    u_clipped[over] = u_clipped[over] / uv_sum[over]
    v_clipped[over] = v_clipped[over] / uv_sum[over]

    v0 = C - A
    v1 = B - A
    P_proj = A + u_clipped.unsqueeze(1) * v0 + v_clipped.unsqueeze(1) * v1

    # If already inside, keep P. Otherwise, use projection.
    final_P = torch.where(inside.unsqueeze(1), P, P_proj)

    return final_P[:, 0], final_P[:, 1]  # x_proj, y_proj

e = 0

for i in range(1000):
    p_layout = Path(f"./Python_Layouts/Layout_{i + 1}.txt")

    if p_layout.exists():
        data = np.loadtxt(p_layout)

        x = torch.tensor(data[:, 0], dtype = torch.float32)
        y = torch.tensor(data[:, 1], dtype = torch.float32)
        e = i + 1

if e > 0:
    print(f"Updated Layout {e} is initialized")

else:
    print("First Layout is initialized")

class LearnableXY(torch.nn.Module):
    def __init__(self, x_init, y_init):
        super().__init__()
        self.x = torch.nn.Parameter(x_init)
        self.y = torch.nn.Parameter(y_init)

    def forward(self):
        return self.x, self.y

xy_module = LearnableXY(x, y)

def push_apart(module, min_dist = 2 * TankRadius):
    x, y = module()  # Correctly calls forward()
    coords = torch.stack([x, y], dim=1)  # shape (N, 2)

    with torch.no_grad():
        for i in range(coords.shape[0]):
            diffs = coords[i] - coords
            dists = torch.norm(diffs, dim=1)
            mask = (dists < min_dist) & (dists > 0)

            for j in torch.where(mask)[0]:
                direction = diffs[j] / dists[j]
                displacement = 0.5 * (min_dist - dists[j]) * direction
                coords[i] += displacement
                coords[j] -= displacement

        # Update learnable parameters in-place
        module.x.data.copy_(coords[:, 0])
        module.y.data.copy_(coords[:, 1])

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# #Now we do the optimization step
# SWGOopt = True
# optimizer = torch.optim.SGD(xy_module.parameters(), lr = 5, momentum = .9)
# 
# if path.exists():
#     optimizer.load_state_dict(checkpoint["optimizer_state_dict"])
#     num_epoch = checkpoint.get("epoch") + 1
#     loss = checkpoint.get("loss")
# 
#     print(f"Optimizer is initialized from the last epoch {num_epoch}")
# 
# else:
#     num_epoch = 0
#     print("Optimizer is initialized")
# 
# max_grad = 10.
# 
# Nbatch = 500
# 
# if num_epoch < 20:
#     Nfinetune = 2500
# 
# elif num_epoch >= 20:
#     Nfinetune = 5000
# 
# U_vals = []
# U_pr_vals = []
# U_e_vals = []
# U_th_vals = []
# 
# for epoch in range(num_epoch, num_epoch + 100):
#     x1, y1 = xy_module()
# 
#     #Batch Generation:
#     N_list = []
#     T_list = []
#     labels_batch = torch.zeros((Nbatch, 5))
# 
#     for i in range(Nbatch):
#         N, T, x0, y0, E, theta, phi = GenerateShowers(x1, y1)
# 
#         N_list.append(N)
#         T_list.append(T)
#         labels_batch[i] = torch.tensor([x0, y0, E, theta, phi], dtype = torch.float32)
# 
#     x = x1.unsqueeze(0).repeat(Nbatch, 1)
#     y = y1.unsqueeze(0).repeat(Nbatch, 1)
# 
#     events_n_batch = torch.stack(N_list).squeeze(-1)  # shape: (Nbatch, Nunits)
#     events_t_batch = torch.stack(T_list).squeeze(-1)
# 
#     events_batch = torch.stack((x, y, events_n_batch, events_t_batch), dim = 2)
# 
#     model.eval()
# 
#     preds_batch = model(events_batch.view(Nbatch, -1))
# 
#     #Denormalize the predictions
#     preds_x = preds_batch[:, 0] * 5000
#     preds_y = preds_batch[:, 1] * 5000
#     preds_e, preds_th, preds_phi = DenormalizeLabels(preds_batch[:, 2], preds_batch[:, 3],
#                                                                                 preds_batch[:, 4])
# 
#     #Compute the reconstructability score for each event:
#     r_score = reconstructability(events_batch[:, :, 2])
#     density = Nbatch / ((labels_batch[:, 0].max() - labels_batch[:, 0].min()) *
#                         (labels_batch[:, 1].max() - labels_batch[:, 1].min()))
# 
#     #Compute Utility:
#     U = 1e-2 * U_TH(preds_th, labels_batch[:, 3], r_score) + U_E(preds_e, labels_batch[:, 2], r_score) + U_PR(r_score) / torch.sqrt(density)
# 
#     #Save the utility values to plot
#     U_vals.append(U.item())
#     U_pr_vals.append((U_PR(r_score) / torch.sqrt(density)).item())
#     U_e_vals.append(U_E(preds_e, labels_batch[:, 2], r_score).item())
#     U_th_vals.append(1e-2 * U_TH(preds_th, labels_batch[:, 3], r_score).item())
# 
#     #sym_loss = symmetry_loss(x1, y1, n_symmetry = 3)
#     print(f"Utility: {U:.2f}")
# 
#     #Use utility as - Loss, we have a penalty term to make configuration symmetric
#     Loss = - U #+ lambda_sym * sym_loss
# 
#     Loss.backward()
# 
#     torch.nn.utils.clip_grad_norm_(xy_module.parameters(), max_norm = max_grad)
# 
#     optimizer.step()
# 
#     with torch.no_grad():
#         push_apart(xy_module)
# 
#     #This part is done to keep the detectors inside the site
#     """
#     with torch.no_grad():
#         x_proj, y_proj = project_to_triangle(x1.view(-1), y1.view(-1))
#         x1.copy_(x_proj)
#         y1.copy_(y_proj)
#     """
# 
#     optimizer.zero_grad()
# 
#     #Now we need to generate new events that with the new layout so that we can fine tune our NN when it's necessary
#     if (epoch + 1) % 5 == 0:
#         print(f"Fine Tune at epoch {epoch + 1}")
# 
#         finetune_events = torch.zeros((Nfinetune, Nunits, 4))
#         finetune_trues = torch.zeros((Nfinetune, 5))
# 
#         with torch.no_grad():
#             x2, y2 = xy_module()
#             x = x2.detach()
#             y = y2.detach()
# 
#             #Generate events to fine tune the network
#             for i in range(Nfinetune):
#                 N, T, x0, y0, E, theta, phi = GenerateShowers(x, y)
# 
#                 x0 /= 5000
#                 y0 /= 5000
#                 E, theta, phi = NormalizeLabels(E, theta, phi)
# 
#                 finetune_events[i] = torch.tensor(np.column_stack((x, y, N, T)))
#                 finetune_trues[i] = torch.tensor([x0, y0, E, theta, phi], dtype = torch.float32)
# 
#         ReconstructionNN = model
#         ReconstructionNN.train()
#         criterion = nn.MSELoss()
#         optimizerNN = torch.optim.Adam(ReconstructionNN.parameters(), lr = 5e-5)
# 
#         dataset = TensorDataset(finetune_events, finetune_trues)
#         dataloader = DataLoader(dataset, batch_size = 32, shuffle = True, drop_last = True, num_workers = 4)
# 
#         for j in range(5):
#             for ft_batch, ft_trues in dataloader:
#                 batch_size = ft_batch.size(0)
# 
#                 train_x = ft_batch.view(batch_size, -1)
# 
#                 train_y = ft_trues.view(batch_size, 5)
# 
#                 #Train the network
#                 outputs = ReconstructionNN(train_x)
# 
#                 lossT = criterion(outputs, train_y)
# 
#                 lossT.backward()
#                 optimizerNN.step()
# 
#                 optimizerNN.zero_grad()
# 
#     #I will save the layouts and weights here so that I can stop whenever and continue later
#     torch.save({"epoch": epoch, "loss": Loss, "model_state_dict": model.state_dict(),
#                 "optimizer_state_dict": optimizer.state_dict()}, "./NN_Files/checkpoint.pth")
# 
#     np.savetxt(f"./Python_Layouts/Layout_{epoch + 1}.txt", np.column_stack((x1.detach().numpy(), y1.detach().numpy())))

a, b = Layouts()

plt.figure(figsize = [6, 6])
plt.scatter(x.detach(), y.detach(), color = "red", alpha = .8, label = "Final Layout")
plt.scatter(a, b, color = "blue", alpha = .3, label = "Initial Layout")
#plt.plot([-3800, 1200, 1200, -3800], [1500, 1500, -4100, 1500], "k--", label = "SWGO Site")

#Add Shower Simulation Area
#ax = plt.gca()
#rect = patches.Rectangle((-3000, -3000), 6000, 6000, linewidth=1.5, edgecolor='green', facecolor='green',
                         #alpha=0.1, label='Shower Simulation Area')
#ax.add_patch(rect)

plt.grid()
plt.xlabel("x [m]")
plt.ylabel("y [m]")
plt.title("Position of the detectors")
plt.legend()
plt.xlim((-3000, 3000))
plt.ylim((-3000, 3000))
plt.show()

utility_path = Path("./Python_Layouts/Utilities.txt")

if utility_path.exists():
    data = np.loadtxt(utility_path)
    u_t = data
    #u_p = data[:, 1]
    #u_e = data[:, 2]
    #u_a = data[:, 3]

    u_t = np.append(u_t, np.array(U_vals).ravel())
    #u_p = np.append(u_p, np.array(U_pr_vals).ravel())
    #u_e = np.append(u_e, np.array(U_e_vals).ravel())
    #u_a = np.append(u_a, np.array(U_th_vals).ravel())

    #data = np.column_stack((u_t, u_p, u_e, u_a))

    np.savetxt(utility_path, u_t)

else:
    u_t = U_vals
    #u_p = U_pr_vals
    #u_e = U_e_vals
    #u_a = U_th_vals

    #data = np.column_stack((u_t, u_p, u_e, u_a))
    np.savetxt(utility_path, u_t)

mean_ut = [np.mean(u_t[i - 4: i]) for i in range(4, len(u_t))]

plt.plot(u_t, color = "black", linestyle = "none", marker = "o", linewidth = .5, label = "Total Utility")
plt.plot(np.arange(4, len(u_t)), mean_ut, linestyle = "-", linewidth = 2, label = "Mean Utility")
#plt.plot(u_p, color = "orange", linestyle = "-.", label = "Reconstructability Utility")
#plt.plot(u_e, color = "green", linestyle = "-.", label = "Energy Utility")
#plt.plot(u_a, color = "purple", linestyle = "-.", label = "Angle Utility")
plt.legend()
plt.grid()
plt.xlabel("Epoch")
plt.ylabel("Utility Score")
plt.ylim((0, np.max(u_t) + 1000))
plt.title("Utility Values per Optimization Step")
plt.show()

